// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE-nidhwCBj1eW1MIk94JyROUhQBsrwF0',
    appId: '1:563017252610:web:98b05745e637d8d22e0c1b',
    messagingSenderId: '563017252610',
    projectId: 'fir-1-5da9e',
    authDomain: 'fir-1-5da9e.firebaseapp.com',
    storageBucket: 'fir-1-5da9e.appspot.com',
    measurementId: 'G-GGRRM18DE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2AMqV9HtRGeuitG9D5rn0iEHzhKDVeTQ',
    appId: '1:563017252610:android:e17b7f4651a9d2d22e0c1b',
    messagingSenderId: '563017252610',
    projectId: 'fir-1-5da9e',
    storageBucket: 'fir-1-5da9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDaa_13-RzPzH5Qu2c6L1RSTQFKmeBcUQ',
    appId: '1:563017252610:ios:23829904a30222992e0c1b',
    messagingSenderId: '563017252610',
    projectId: 'fir-1-5da9e',
    storageBucket: 'fir-1-5da9e.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDaa_13-RzPzH5Qu2c6L1RSTQFKmeBcUQ',
    appId: '1:563017252610:ios:c1358314930b67622e0c1b',
    messagingSenderId: '563017252610',
    projectId: 'fir-1-5da9e',
    storageBucket: 'fir-1-5da9e.appspot.com',
    iosBundleId: 'com.noman.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE-nidhwCBj1eW1MIk94JyROUhQBsrwF0',
    appId: '1:563017252610:web:99e7fadd354112402e0c1b',
    messagingSenderId: '563017252610',
    projectId: 'fir-1-5da9e',
    authDomain: 'fir-1-5da9e.firebaseapp.com',
    storageBucket: 'fir-1-5da9e.appspot.com',
    measurementId: 'G-46LNP7N6V8',
  );
}
